### PR TITLE
gen2 record/replay

### PR DESCRIPTION
**Pull request by Erol444**
**This functionality (both recording and replaying) will be moved to `depthai/depthai_demo.py` script in the future.**

-------------------------

added record.py/replay.py scripts. Also added */data/* to gitignore.

TODO:
- Optionally save depth as well and when replaying, use saved depth instead of mono frames & stereo node
- Add readme
- Add demo video/gif
-

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
This will be so nice to have in depthai_demo.py.  And I really like the idea that was brought up internally of adding some kind of "dataset sharing" functionality, so community (and we) could prepare some common use case datasets (like driving) and whole community could easily use it by just specifying the name into the depthai_demo argument.  That will be so awesome for folks to be able to replicate work.

**Review by dhruvsheth-ai — COMMENTED** [review]
https://github.com/luxonis/depthai-experiments/blob/gen2-replay/gen2-replay/README.md#replay-usage

**Comment by Erol444** [comment]
> https://github.com/luxonis/depthai-experiments/blob/gen2-replay/gen2-replay/README.md#replay-usage
> 
> Just a suggestion, the -p comment could be changed to `Path of the stored data` to avoid confusion with the record.py path comment. :)
> 
> This script is really useful btw!!

you are totally right, we will keep that in mind when migrating this functionality into depthai_demo, thanks :)

**Comment by Erol444** [comment]
a (very) late update: we have merged this functionality in a separate PR: https://github.com/luxonis/depthai-experiments/pull/202

**Pull request closed without merging**
