### PR TITLE
[demo] multiple devices on host

### PR DESCRIPTION
**Pull request by Erol444**
Since few of our users have already had questions about this topic, I added demo code for using multiple devices on a host. Copied/edited code from `depthai-python` branch [gen2_try_multi_device](https://github.com/luxonis/depthai-python/blob/gen2_try_multi_device/examples/06_rgb_full_resolution_saver.py). @alex-luxonis hopefully we can delete your branch after we merge this PR.

- After PR we should also reference this demo from our [docs page about this](https://docs.luxonis.com/projects/api/en/latest/tutorials/multiple)

### CODE REVIEW

**Comment by Erol444** [comment]
Just now I see that there's already a PR opened for this: https://github.com/luxonis/depthai-experiments/pull/44 @VanDavv  should we rather use your code with threading?

**Comment by Luxonis-Brandon** [comment]
I thought I had seen such a thing before.  I should have brought up.  So either way we should make sure to get one of them merged.  Thanks for pushing on this.

**Comment by Erol444** [comment]
Demo gif
multiple-devices-demo

**Comment by Luxonis-Brandon** [comment]
That's a great demo GIF.  Good idea.  :-)

**Review by VanDavv — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
