### PR TITLE
Pipeline GUI Editor

### PR DESCRIPTION
**Pull request by AsherVo**
Visual editor for DAI pipelines! Showcased in the #pipeline-builder-gen2 channel in the discord.

### CODE REVIEW

**Comment by VanDavv** [comment]
@AsherVo thanks a ton for the PR! I received the following error when trying to run the pipeline visualizer

```
Traceback (most recent call last):
  File "pipeline_editor.py", line 4, in <module>
    from Qt import QtWidgets
ModuleNotFoundError: No module named 'Qt'
```

Could you update the requirements file with the Qt package you used (don't know if it's `pyside2`, `pyside6`, `pyqt5` or other)

**Comment by themarpe** [comment]
Hi @AsherVo thanks for the PR
@VanDavv i think it might make sense to move this PR to depthai gui repo in either a new branch or alongside

**Comment by VanDavv** [comment]
I think we can actually replace depthai-gui with this project @themarpe, as the old one is outdated anyways,  good idea

**Comment by AsherVo** [comment]
@VanDavv The requirements should be fixed, sorry about that!

Also I had no idea that the depthai-gui repo existed. Let me know if I should do a PR there instead.

**Comment by themarpe** [comment]
> Also I had no idea that the depthai-gui repo existed. Let me know if I should do a PR there instead.

Please do a PR there instead, will suit better. (preferably replacing the whole existing codebase or better going to `main` branch, to be consistent with other repos)

And @VanDavv, once the PR is opened, feel free to either branch it as main and "out branch" the old gui, or some other way you see fit.
Later we can unfork it from the initial GUI base as such: https://ralphjsmit.com/unfork-github-repo/

**Comment by VanDavv** [comment]
thanks both, I'll wait for your PR to GUI repo @AsherVo just so GitHub recons you've created this code and then I'll make sure this gets mainlined, will have to both run it on different platforms/python versions to know where it's working and analyse the code to understand it in and out to be able to make future changes

**Pull request closed without merging**
