### PR TITLE
fix: incoherent gaze & distorted pose 3d-axis

### PR DESCRIPTION
**Pull request by auphofBSF**
The Gaze is incoherent with the pose and eye gaze angle. Additionally the 3d-axis drawn for a pose is distorted and incorrect for most pose angles,

The top line of the following image shows examples of incoherence and distortion, the bottom line is captures at similar times with the fixes in this PR
image

The comprehension iteration of pose_nn.get().values() is not producing the  required order Yaw, Role,Pitch
Debugger observation shows it is reversed `['angle_p_fc', 'angle_r_fc', 'angle_y_fc']` from the following list comprehension
`                 self.pose = [val[0][0] for val in to_tensor_result(pose_nn.get()).values()]`
As a result the Gaze model being fed with a reversed pose (Pitch, Roll, Yaw)

The 3d Pose Axis indicator is distorted, refactor to the code from OpenVino Open Model Zoo - Gaze Estimation Demo
https://github.com/openvinotoolkit/open_model_zoo/blob/b1ff98b64a6222cf6b5f3838dc0271422250de95/demos/gaze_estimation_demo/cpp/src/results_marker.cpp#L50 produces an apparently correct  pose 3d axis indicator, shown in above image

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Thank you!

**Comment by Luxonis-Brandon** [comment]
CC: @VanDavv and @Erol444

**Comment by VanDavv** [comment]
Thanks! I'll check that today/tomorrow and circle back

**Comment by VanDavv** [comment]
Works perfectly, thanks a lot for your contribution @auphofBSF !

**Pull request merged**
