### PR TITLE
Add age/gender recognition example

### PR DESCRIPTION
**Pull request by VanDavv**
# Gen2 Age & Gender recognition

This example demonstrates how to run 2 stage inference on DepthAI using Gen2 Pipeline Builder.
First, a face is detected on the image and then the cropped face frame is sent to age gender recognition network, which
produces the estimated results

## Demo

[Gen2 Age & Gender recognition](https://www.youtube.com/watch?v=PwnVrPaF-vs "Age/Gender recognition on DepthAI")

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
image
So actually it's pretty close on my age.  Usually right around what others guess, and close to my actual age.

**Review by Luxonis-Brandon — APPROVED** [review]
LGTM on Mac.

**Comment by pamolloy** [comment]
Looks really cool and overall worked great!

It may just be my setup, but when I exit by hitting `q` I see the following. I did run `pip install -r requirements.txt` so the version of DepthAI should be correct.

```
Traceback (most recent call last):
  File "/home/philip/repos/work/luxonis/depthai-experiments/gen2-age-gender/main.py", line 170, in <module>
    cap.release()
NameError: name 'cap' is not defined
```

And at one point I saw the following, but couldn't reproduce it:

```
Traceback (most recent call last):
  File "/home/philip/repos/work/luxonis/depthai-experiments/gen2-age-gender/main.py", line 133, in <module>
    bboxes = bboxes[:np.where(bboxes == -1)[0][0]]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by InzamamAnwar** [comment]
I have tested the code an I can reproduce the error. It's due to the fact that some times there is no `-1` in the detection (bboxes). If you comment out that part where the bboxes are sliced at the point where we get `-1`, then it will run smoothly.

**Comment by Luxonis-Brandon** [comment]
Thanks for the test @InzamamAnwar !  CC: @VanDavv .

**Comment by VanDavv** [comment]
Thanks for the testing @Luxonis-Brandon  @pamolloy and @InzamamAnwar . I was able to reproduce it and fixed, also added a small change that will improve the stability of detections

**Comment by Luxonis-Brandon** [comment]
Sweet, thanks!  I'd say this is good to merge then @VanDavv !  (Also, I'm younger today.  I don't feel younger.)

image

**Comment by VanDavv** [comment]
Thanks all!

**Comment by rexn8r** [comment]
hi guys

great example. 

one question.

how do i get the x,y,z depth of the face from the face detection using gen2-age-gender sample?

i want to calculate distance of the face along with age and gender.

i looked at spatial detection but to be honest, the API is overwhelming and i couldn't figure out 

any guidance would be appreciated.

thanks
rex

**Comment by Luxonis-Brandon** [comment]
We will make an example that does this.  We should have this out this week.  We'll likely add it to this example.

Thanks,
Brandon

**Comment by Erol444** [comment]
Hello @rexn8r , refactored demo here: https://github.com/luxonis/depthai-experiments/pull/275 you could also use x/y coordinates, but for visualization purposes we only show z :)
Thanks, Erik

**Comment by Luxonis-Brandon** [comment]
Sweet thanks!

**Pull request merged**
