### PR TITLE
Added lazer mode

### PR DESCRIPTION
**Pull request by LCTyrell**
Added missing and needed lazer mode! -)

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Thanks.  Can't wait to play with it!

**Comment by VanDavv** [comment]
I have just tested it and works great! LGTM

https://user-images.githubusercontent.com/5244214/107849253-5299e100-6dfa-11eb-90dd-e7f9e98a1a55.mp4

**Comment by Luxonis-Brandon** [comment]
Thanks!  So cool.  Let's merge it.  :-)

**Comment by VanDavv** [comment]
Thanks @LCTyrell, just merged

**Pull request merged**
