### PR TITLE
Get RGB frame working with point cloud.

### PR DESCRIPTION
**Pull request by mribbons**

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Thanks @mribbons!  CC: @luxonis-sachin

**Comment by Luxonis-Brandon** [comment]
Thanks @mribbons!  CC: @luxonis-sachin

**Comment by saching13** [comment]
Since there are better improvements in #112 can we close this ?

**Comment by mribbons** [comment]
@saching13 The only reason I made a different branch and PR for #112 was that it requires the library versions as per luxonis:camera_demo_rgb_stereo. The code in my #111 will run against master... But I guess the recipient won't have access to this change anyway. Happy to close this one.

**Pull request closed without merging**
