### PR TITLE
Gen2 OCR: Update depthai lib to latest

### LINKED ISSUE #75: Gen2 OCR Demo
[Error] Reported while running Gen2 OCR example on armv7l;
Using libraries -
numpy==1.19.5
opencv-python==4.5.1.48
depthai==0.0.2.1+e88c98c8a7681dd16cd754a832df1165380ac305

Error -
```bash
(venv2) pi@raspberrypi:~/depthai-experiments/gen2-ocr $ python3 main.py 
main.py:15: DeprecationWarning: setCamId() is deprecated, use setBoardSocket() instead.
  colorCam.setCamId(0)
terminate called without an active exception
Aborted
```

### PR DESCRIPTION
**Pull request by szabi-luxonis**
Updated depthai lib and code to match latest changes for gen2-ocr.
Should fix #75

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Works for me.  One small note for later.  The detect text flashes.  Makes it a bit tricky to screenshot, but let's save that for another time.
image

**Review by Luxonis-Brandon — APPROVED** [review]

**Comment by dhruvsheth-ai** [comment]
2021-03-04-192440_800x480_scrot

Works well for me as well. Might require stabalization later

**Comment by Luxonis-Brandon** [comment]
Thanks.  What do you mean by stabilization?  Just not 100% sure which form you are talking about (firmware, optical, or like tracking of detected text sort of thing).

**Comment by dhruvsheth-ai** [comment]
Sorry, I Used a bit too generalized term. Similar to what you mentioned, it flashes a lot. Inference is too quick, and each second many frames are Classified. Makes it just a bit hard to detect text and read it before it disappears

**Comment by Luxonis-Brandon** [comment]
Thanks.  Actually if you have a second would you mind making an issue about this for tracking purposes?

**Comment by dhruvsheth-ai** [comment]
Sure

**Pull request merged**
