### PR TITLE
Add WLS filter example

### PR DESCRIPTION
**Pull request by szabi-luxonis**
Add wls filter example:
Takes `rectified_right` and `disparity` streams and performs WLS filtering.
https://docs.opencv.org/master/d3/d14/tutorial_ximgproc_disparity_filtering.html

Run as 
```
./install_dependencies.sh
./main.py
```

### CODE REVIEW

**Comment by alex-luxonis** [comment]
Would it be better to use the `rectified_right` stream (after un-flipping) instead of `right`? As that's the one perfectly matched with the disparity. It helped a bit with the point cloud visualization that @saching13 made.

**Comment by szabi-luxonis** [comment]
Thanks @alex-luxonis , Done in eb3c6a1

**Comment by Luxonis-Brandon** [comment]
On Mac OS (version below) I see this:
```
Traceback (most recent call last):
  File "./main.py", line 57, in <module>
    wls_filter = cv2.ximgproc.createDisparityWLSFilterGeneric(lr_check)
AttributeError: module 'cv2.cv2' has no attribute 'ximgproc'
```

image

**Comment by Luxonis-Brandon** [comment]
Seems like this might solve it:
https://stackoverflow.com/questions/57427233/module-cv2-cv2-has-no-attribute-ximgproc

Going to give it a shot now.

**Comment by szabi-luxonis** [comment]
run `./install_dependencies.sh` @Luxonis-Brandon 
See readme.txt

**Comment by Luxonis-Brandon** [comment]
It is looking like I did not have `opencv-contrib-python` installed.  Trying that now with `python3 -m pip install opencv-contrib-python`

**Comment by Luxonis-Brandon** [comment]
Ah thanks @szabi-luxonis .  My bad. :-)

**Comment by Luxonis-Brandon** [comment]
Weird, it looks like same error despite having read the instructions this time:

```
leeroy@DESKTOP-OGSI4CI wls-filter % ./install_dependencies.sh 
Looking in indexes: https://pypi.org/simple, https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local/
Ignoring opencv-python: markers 'platform_machine == "armv7l"' don't match your environment
Ignoring opencv-contrib-python: markers 'platform_machine == "armv7l"' don't match your environment
Ignoring open3d: markers 'platform_machine != "armv7l" and sys_platform == "linux"' don't match your environment
Requirement already satisfied: numpy==1.18.3 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.18.3)
Requirement already satisfied: opencv-python==4.2.0.34 in /Users/leeroy/Library/Python/3.7/lib/python/site-packages (from -r requirements.txt (line 2)) (4.2.0.34)
Collecting opencv-contrib-python==4.2.0.34
  Downloading opencv_contrib_python-4.2.0.34-cp37-cp37m-macosx_10_9_x86_64.whl (60.3 MB)
     |████████████████████████████████| 60.3 MB 12.4 MB/s 
Requirement already satisfied: requests==2.24.0 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (2.24.0)
Requirement already satisfied: argcomplete==1.12.0 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (1.12.0)
Collecting depthai==0.2.0.1+8cf9e4125e54701cd71a50d04cb2d6f30907ab0e
  Downloading https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local/depthai/depthai-0.2.0.1%2B8cf9e4125e54701cd71a50d04cb2d6f30907ab0e-cp37-cp37m-macosx_10_9_x86_64.whl (2.8 MB)
     |████████████████████████████████| 2.8 MB 997 kB/s 
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests==2.24.0->-r requirements.txt (line 8)) (2020.4.5.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests==2.24.0->-r requirements.txt (line 8)) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests==2.24.0->-r requirements.txt (line 8)) (1.25.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests==2.24.0->-r requirements.txt (line 8)) (2.9)
Requirement already satisfied: importlib-metadata<2,>=0.23; python_version == "3.7" in /usr/local/lib/python3.7/site-packages (from argcomplete==1.12.0->-r requirements.txt (line 9)) (1.7.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/site-packages (from importlib-metadata<2,>=0.23; python_version == "3.7"->argcomplete==1.12.0->-r requirements.txt (line 9)) (3.1.0)
Installing collected packages: opencv-contrib-python, depthai
  Attempting uninstall: opencv-contrib-python
    Found existing installation: opencv-contrib-python 4.4.0.44
    Uninstalling opencv-contrib-python-4.4.0.44:
      Successfully uninstalled opencv-contrib-python-4.4.0.44
  Attempting uninstall: depthai
    Found existing installation: depthai 0.2.0.1+e7332dd90a143c80f75453cb58c7cf0115792905
    Uninstalling depthai-0.2.0.1+e7332dd90a143c80f75453cb58c7cf0115792905:
      Successfully uninstalled depthai-0.2.0.1+e7332dd90a143c80f75453cb58c7cf0115792905
Successfully installed depthai-0.2.0.1+8cf9e4125e54701cd71a50d04cb2d6f30907ab0e opencv-contrib-python-4.2.0.34
```
And then running it:
```
leeroy@DESKTOP-OGSI4CI wls-filter % ./main.py
XLink initialized.
Sending internal device firmware
Successfully connected to device.
Loading config file
Attempting to open stream config_d2h
watchdog started 
Successfully opened stream config_d2h with ID #0!
Closing stream config_d2h: ...
Closing stream config_d2h: DONE.
EEPROM data: valid (v3)
  Board name     : BW1092
  Board rev      : R0M0E0
  HFOV L/R       : 71.86 deg
  HFOV RGB       : 68.7938 deg
  L-R   distance : 4 cm
  L-RGB distance : 1 cm
  L/R swapped    : yes
  L/R crop region: center
  Calibration homography right to left (legacy, please consider recalibrating):
    1.006261,   -0.006620,   -3.711140,
   -0.000918,    0.993052,   10.677346,
    0.000010,   -0.000018,    1.000000,
CNN configurations read: /Users/leeroy/depthai-experiments/wls-filter/models/landmarks-regression-retail-0009/landmarks-regression-retail-0009.json
depthai: Calibration file is not specified, will use default setting;
config_h2d json:
{"_board":{"calib_data":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"mesh_left":[0.0],"mesh_right":[0.0]},"_load_inBlob":true,"_pipeline":{"_streams":[{"name":"disparity"},{"name":"rectified_right"}]},"ai":{"NCEs":2,"blob0_size":532288,"blob1_size":0,"calc_dist_to_bb":false,"camera_input":"right","cmx_slices":14,"keep_aspect_ratio":true,"num_stages":1,"shaves":14},"app":{"sync_video_meta_streams":true},"board":{"clear-eeprom":false,"left_fov_deg":69.0,"left_to_rgb_distance_m":0.0,"left_to_right_distance_m":0.03500000014901161,"name":"","override-eeprom":false,"revision":"","rgb_fov_deg":69.0,"stereo_center_crop":false,"store-to-eeprom":false,"swap-left-and-right-cameras":false},"camera":{"mono":{"fps":30.0,"resolution_h":720,"resolution_w":1280},"rgb":{"fps":30.0,"resolution_h":1080,"resolution_w":1920}},"depth":{"confidence_threshold":0.5,"depth_limit_mm":10000,"lr_check":false,"median_kernel_size":7,"padding_factor":0.30000001192092896,"warp_rectify":{"edge_fill_color":-1,"mirror_frame":true,"use_mesh":false}},"ot":{"confidence_threshold":0.5,"max_tracklets":20}}
size of input string json_config_obj to config_h2d is ->1483
size of json_config_obj that is expected to be sent to config_h2d is ->1048576
Attempting to open stream config_h2d
Successfully opened stream config_h2d with ID #1!
Writing 1048576 bytes to config_h2d
!!! XLink write successful: config_h2d (1048576)
Closing stream config_h2d: ...
Closing stream config_h2d: DONE.
Creating observer stream host_capture: ...
Attempting to open stream host_capture
Successfully opened stream host_capture with ID #0!
Creating observer stream host_capture: DONE.
Read: 532288
Attempting to open stream inBlob
Successfully opened stream inBlob with ID #1!
Writing 532288 bytes to inBlob
!!! XLink write successful: inBlob (532288)
Closing stream inBlob: ...
Closing stream inBlob: DONE.
depthai: done sending Blob file /Users/leeroy/depthai-experiments/wls-filter/models/landmarks-regression-retail-0009/landmarks-regression-retail-0009.blob
Attempting to open stream outBlob
Successfully opened stream outBlob with ID #2!
Closing stream outBlob: ...
Closing stream outBlob: DONE.
CNN input width: 48
CNN input height: 48
CNN input num channels: 3
CNN to depth bounding-box mapping: start(280, 0), max_size(720, 720)
Host stream start:disparity
Opening stream for read: disparity
Attempting to open stream disparity
Successfully opened stream disparity with ID #1!
Starting thread for stream: disparity
Started thread for stream: disparity
Host stream start:rectified_right
Opening stream for read: rectified_right
Attempting to open stream rectified_right
Successfully opened stream rectified_right with ID #2!
Starting thread for stream: rectified_right
Started thread for stream: rectified_right
depthai: INIT OK!
=== New data in observer stream host_capture, size: 1
Writing 1 bytes to host_capture
!!! XLink write successful: host_capture (1)
Traceback (most recent call last):
  File "./main.py", line 57, in <module>
    wls_filter = cv2.ximgproc.createDisparityWLSFilterGeneric(lr_check)
AttributeError: module 'cv2.cv2' has no attribute 'ximgproc'
```

I wonder if this is OpenCV issue on MacOS?

**Comment by Luxonis-Brandon** [comment]
Actually following the most-upvoted answer here did fix it:
https://stackoverflow.com/questions/57427233/module-cv2-cv2-has-no-attribute-ximgproc

**Comment by szabi-luxonis** [comment]
Yeah, packages were probably messed up on your mac.. We either should run the install script with python3 -m ... `-U`, or installing in virtual environment, so we don' break other packages.

**Comment by Luxonis-Brandon** [comment]
Yes, agreed, and good call.

**Comment by Luxonis-Brandon** [comment]
image

LGTM.

**Pull request merged**
