### PR TITLE
NanoSAM experiment

### PR DESCRIPTION
**Pull request by tersekmatija**
NanoSAM experiment.

Could be further optimized for performance in the future.

### CODE REVIEW

**Comment by Erol444** [comment]
do we have any video/image for the demo?

**Comment by tersekmatija** [comment]
output_short

**Comment by tersekmatija** [comment]
Updated README @Erol444 Feel free to test out and merge if works as expected.

**Review by Erol444 — APPROVED** [review]

**Review by jakaskerl — APPROVED** [review]
Tested both scripts yesterday, both seem to work great, albeit a little slow (as expected).

**Pull request merged**
