### PR TITLE
Added poe tcp streaming demos

### PR DESCRIPTION
**Pull request by Erol444**
TODO: add readmes

### CODE REVIEW

**Comment by themarpe** [comment]
Modify such that PoE device is the host and other relevant changes

**Comment by Erol444** [comment]
@themarpe Both options (OAK host or client) are in the folder. What relevant changes?

**Comment by reallyedutech** [comment]
Hi, my name is Ryan. 

i have still not clear how to modify those files. So i have questions.

First: Which one is server? OAK-PoE?
Second: How to put the code on OAK-PoE?

If i am on the wrong way please correct me. 

Best regards,

**Comment by Erol444** [comment]
Hello @reallyedutech ,
- Files can be found [here](https://github.com/luxonis/depthai-experiments/tree/TCP_streaming_poe/gen2-poe-tcp-streaming)
- As you can see on the link above, there are 2 folders; one where OAK is host and one where OAK is the client
- When you run `oak.py`, the pipeline will get uploaded to the (connected) OAK camera. Simultaneously you have to run the `host.py` script, so the TCP communication starts.

**Review by themarpe — CHANGES_REQUESTED** [review]
Add a README and some quick tips on running etc...

Otherwise LGTM

**Pull request merged**
