### PR TITLE
Refactor Gaze Estimation example

### PR DESCRIPTION
**Pull request by VanDavv**
Refactored and made it work faster, demo below

[Gaze Example Demo](https://user-images.githubusercontent.com/5244214/106155520-0f483d00-6181-11eb-8b95-a2cb73cc4bac.mp4)

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Wow, looks great - thanks!

**Review by raymondlo84 — COMMENTED** [review]
You may want to also review the requirement.txt or user will see this issue.

ModuleNotFoundError: No module named 'imutils'

**Comment by raymondlo84** [comment]
File "main.py", line 312, in <module>
    Main().run()
  File "main.py", line 302, in run
    if cv2.waitKey(1) == ord('q'):
KeyboardInterrupt
Assertion failed: (pthread_mutexAssertion failed: (pthread_mutex_destroy(mutex) == 0), function _lock(mutex) == 0), function usbusbi_mutex_destroy, file ./os/thi_mutex_lock, file ./os/threads_reads_posix.h, line 58.
posix.h, line 46.
zsh: abort      python3 main.py -cam

... FYI.

**Comment by VanDavv** [comment]
Thanks for the test @raymondlo84 ! 
I just pushed a fix with missing requirement as you've mentioned.
I will also implement a mechanism to exit the threads gracefully, but just out of curiosity - doesn't daemon threads do this already, as stated [here](https://docs.python.org/3/library/threading.html#threading.Thread.daemon)? `The entire Python program exits when no alive non-daemon threads are left` - so does this fix only solve the misleading console prints or is it somehow more beneficial?

**Comment by raymondlo84** [comment]
Last and not least, I think the left and right eye bounding boxes should be scaled accordingly too? It seems now it's statics?

**Comment by VanDavv** [comment]
@raymondlo84 yes, they are scaled statically because it's required by the neural network

**Comment by raymondlo84** [comment]
> Thanks for the test @raymondlo84 !
> I just pushed a fix with missing requirement as you've mentioned.
> I will also implement a mechanism to exit the threads gracefully, but just out of curiosity - doesn't daemon threads do this already, as stated [here](https://docs.python.org/3/library/threading.html#threading.Thread.daemon)? `The entire Python program exits when no alive non-daemon threads are left` - so does this fix only solve the misleading console prints or is it somehow more beneficial?

Good question. =) I need to dig up documentation further as well. But the join is working and just tested it. Yes, the bounding box for left and right eye... Did we do it correctly?

**Comment by raymondlo84** [comment]
> @raymondlo84 yes, they are scaled statically because it's required by the neural network

But the bounding box drawing is not reflecting that. I guess it's a pure UI issue?

**Comment by Luxonis-Brandon** [comment]
Yes, it seems that way.  

So I'm thinking we should merge this (since it's faster) and then circle back to fix that as a separate effort.  Thoughts?

**Comment by VanDavv** [comment]
@raymondlo84 This slight delay in bounding boxes is an issue with synchronization and we're working on this right now, so we'll circle back and improve this example further.

However, on our [discord channel](https://discord.com/channels/790680891252932659/791012940093849600/804629990490505236), user Boris provided a video where the example crashed, and I provided fixes for this issue [here](https://github.com/luxonis/depthai-experiments/pull/51/commits/3b8e6dc581ca029cae0e13345b3ec9a3bbda2d52).

@pamolloy @themarpe can you please take a look if you can see any issues with this refactor or some possible improvements to be made?

**Review by pamolloy — APPROVED** [review]

**Comment by pamolloy** [comment]
Looks great! I did just notice the following when I exit:
```
python3: io.c:2115: handle_events: Assertion `ctx->pollfds_cnt >= internal_nfds' failed.
Aborted (core dumped)
```

**Comment by VanDavv** [comment]
@pamolloy I have noticed similar issue when I'm unable to join the threads (a graceful thread exit I added last time didn't work), so then I just exit the app and use a fact that they're daemon threads and they have to exit. This message may come from DepthAI when it's terminated in a middle of an operation

**Comment by themarpe** [comment]
The `Abort` issue stems from XLink and the way it operates with libusb. Something to be checked in the future when time allows.

**Review by themarpe — APPROVED** [review]
LGTM

**Comment by raymondlo84** [comment]
> @pamolloy I have noticed similar issue when I'm unable to join the threads (a graceful thread exit I added last time didn't work), so then I just exit the app and use a fact that they're daemon threads and they have to exit. This message may come from DepthAI when it's terminated in a middle of an operation

Screen Shot 2021-01-29 at 11 03 45 AM

It got the same crash again, without the join thread. That's now very weird. =) 

Assertion failed: (pthread_mutexAssertion failed: (pthread_mutex_destroy(mutex) == 0), function _lock(mutex) == 0), function usbusbi_mutex_destroy, file ./os/thi_mutex_lock, file ./os/threads_reads_posix.h, line 58.

....

-ray

**Comment by raymondlo84** [comment]
> @raymondlo84 This slight delay in bounding boxes is an issue with synchronization and we're working on this right now, so we'll circle back and improve this example further.
> 
> However, on our [discord channel](https://discord.com/channels/790680891252932659/791012940093849600/804629990490505236), user Boris provided a video where the example crashed, and I provided fixes for this issue [here](https://github.com/luxonis/depthai-experiments/pull/51/commits/3b8e6dc581ca029cae0e13345b3ec9a3bbda2d52).
> 
> @pamolloy @themarpe can you please take a look if you can see any issues with this refactor or some possible improvements to be made?

Oh, delay yes. But the bounding box (SIZE) for the eyes seem to be off and that throws me off a bit more.

I agree with Brandon we should open a new PR to track that. This thread should focus on thread parallelization and debugs.

**Comment by Luxonis-Brandon** [comment]
Thanks both.  And also given that the other (current version) is so slow/laggy, and that this is generally better - we should merge this and then do issue tracking off of the merged version.

Otherwise many will likely come upon the other example, say `wow, this device sucks!`, but it in the drawer, and move along.

**Comment by raymondlo84** [comment]
> Thanks both. And also given that the other (current version) is so slow/laggy, and that this is generally better - we should merge this and then do issue tracking off of the merged version.
> 
> Otherwise many will likely come upon the other example, say `wow, this device sucks!`, but it in the drawer, and move along.

=D Take the bullet and move on! but let's keep tracking these refinements. 

-ray

**Comment by Luxonis-Brandon** [comment]
> but let's keep tracking these refinements.

Yes, for sure!  So to confirm, the third issue (aside from the left/right drawing and the latency) is the crash upon termination of the demo, right?  If so, I'll make an issue for that.

**Comment by VanDavv** [comment]
@raymondlo84 the bounding boxes for eyes are generated on the UI, so they can be changed. However, they are now reflecting what is being sent to the neural network. It accepts eye images scaled to 60x60, and from landmarks neural network I receive a single eye point, so using `padded_point(..., padding=30, ...)` is producing a correct bounding box that I can send further.

This is also why this bounding box is sometimes too big / too small - as it doesn't take the face dimensions into account.

One fix for this, that would be fairly easy to do, is to somehow correlate the face dimensions with eye size, so that for given face width/height we can estimate the eyes width/height. This way, we could draw a better bounding box and the scaled image for nn would contain less non-eye parts, so it may also improve efficiency

**Pull request merged**
