### PR TITLE
Add gen2 example of using multiple devices

### PR DESCRIPTION
**Pull request by VanDavv**
TODO:
- use `with` to aquire device
- test on Windows, MacOS and Linux
- Prepare README.md with demo video

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
What's the status of this PR?  Is it workable?  And does this technique work on Windows?  (I am assuming it is using the MX serial number.)

**Comment by VanDavv** [comment]
@Luxonis-Brandon I've added TODO items, it lacks testing and description, I've put it quickly for one of our users

**Comment by Luxonis-Brandon** [comment]
Thanks makes sense!

**Comment by Erol444** [comment]
We have merged this feature already: https://github.com/luxonis/depthai-experiments/pull/103

**Pull request closed without merging**
