### PR TITLE
Roboflow App Integration

### PR DESCRIPTION
**Pull request by tomek-l**
This is a demo app for creating datasets in an automated way using OAK camera with Mobilenet-SSD object detector and roboflow app.

Usage details are described in `README.md` Since the last review I have added an option for uploading images in arbitrary resolution using the synchronized `NV12` frames.

### CODE REVIEW

**Comment by VanDavv** [comment]
Thanks a lot @tomek-l ! Will give it a try and circle back

**Comment by VanDavv** [comment]
Hi @tomek-l,
I tried to run the script and it failed with the following issue

```
INFO: Uploaded image with ID: WXhyfRvH8o7idrl3T3SR
INFO: Auto-uploading grabbed frame with 1 annotations!
INFO: Uploaded image with ID: WXhyfRvH8o7idrl3T3SR
ERROR: failed annotation for image ID: WXhyfRvH8o7idrl3T3SR
{'error': {'message': 'Image not found in dataset.', 'type': 'InvalidParameterException', 'hint': 'The image ID is returned by the upload API.'}}
ERROR: failed annotation for image ID: WXhyfRvH8o7idrl3T3SR
{'error': {'message': 'Image not found in dataset.', 'type': 'InvalidParameterException', 'hint': 'The image ID is returned by the upload API.'}}
```

Ran with the following parameters - `--upload_res 640x360 --autoupload_interval 0.5 --autoupload_threshold 0.7` - and I don't see these images uploaded to roboflow at all

I also prepared a patch to use blobconverter and e.g. face detection network (same input/output dims, just detects faces for simplicity), feel free to use it to ease the setup (with blobconverter, we can download blob dynamically)
```
Index: roboflow-integration/models/download.sh
===================================================================
diff --git a/roboflow-integration/models/download.sh b/roboflow-integration/models/download.sh
deleted file mode 100644
--- a/roboflow-integration/models/download.sh	(revision 7f43e206f0e005879bd611875ac36d1c0ac64ed2)
+++ /dev/null	(revision 7f43e206f0e005879bd611875ac36d1c0ac64ed2)
@@ -1,1 +0,0 @@
-wget https://artifacts.luxonis.com/artifactory/luxonis-depthai-data-local/network/mobilenet-ssd_openvino_2021.4_5shave.blob
Index: roboflow-integration/main.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/roboflow-integration/main.py b/roboflow-integration/main.py
--- a/roboflow-integration/main.py	(revision 7f43e206f0e005879bd611875ac36d1c0ac64ed2)
+++ b/roboflow-integration/main.py	(date 1644496995413)
@@ -1,41 +1,18 @@
 import time
-import json
 import argparse
 
-from pathlib import Path
 from collections import deque, OrderedDict
 from concurrent.futures import ThreadPoolExecutor
 
+import blobconverter
 import cv2
 import depthai as dai
 import numpy as np
 
 from utils.roboflow import RoboflowUploader
 
-BLOB_PATH = "models/mobilenet-ssd_openvino_2021.4_5shave.blob"
-LABELS = [
-    "background",
-    "aeroplane",
-    "bicycle",
-    "bird",
-    "boat",
-    "bottle",
-    "bus",
-    "car",
-    "cat",
-    "chair",
-    "cow",
-    "diningtable",
-    "dog",
-    "horse",
-    "motorbike",
-    "person",
-    "pottedplant",
-    "sheep",
-    "sofa",
-    "train",
-    "tvmonitor",
-]
+BLOB_PATH = blobconverter.from_zoo(name="face-detection-retail-0004", shaves=5)
+LABELS = ["background", "face"]
 
 
 def make_pipeline():
Index: roboflow-integration/requirements.txt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/roboflow-integration/requirements.txt b/roboflow-integration/requirements.txt
--- a/roboflow-integration/requirements.txt	(revision 7f43e206f0e005879bd611875ac36d1c0ac64ed2)
+++ b/roboflow-integration/requirements.txt	(date 1644501261723)
@@ -1,9 +1,11 @@
 certifi==2021.10.8
 charset-normalizer==2.0.9
-depthai==2.13.3.0.dev0+c0d306db16bd76a98ca9b96297e21668c3176277 --extra-index-url https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local/
+--extra-index-url https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local/
+depthai==2.13.3.0.dev0+c0d306db16bd76a98ca9b96297e21668c3176277
 idna==3.3
 numpy==1.21.5
 opencv-python==4.5.5.62
 Pillow==8.4.0
 requests==2.26.0
 urllib3==1.26.7
+blobconverter==1.2.8
diff --git a/roboflow-integration/models/.gitkeep b/roboflow-integration/models/.gitkeep
deleted file mode 100644
index e69de29bb2d1d6434b8b29ae775ad8c2e48c5391..0000000000000000000000000000000000000000
GIT binary patch
literal 0
Hc$@<O00001

```

**Comment by tomek-l** [comment]
I signed up for another account with Roboflow to repeat the process fully from scratch,

1. Inferring from the logs this is what happens:
- We get HTTP 200 response from image upload
- Roboflow API responds with a valid id for the image (`WXhyfRvH8o7idrl3T3SR`)
- When we try to make the annotation call for that same image `WXhyfRvH8o7idrl3T3SR` literally 500ms later, roboflow API is like "I have never met this man in my life" and throws HTTP 404 response.

This issue came up for me twice during development, and then went away after several minutes without any changes. What I suspect is that there might be a minimum time delta between the image getting uploaded, and the image being ready for annotation. I'm unsure whether there's a good way to address that. A dumb, but perhaps an effective way of solving that would be to add `time.sleep(5)` between upload and annotation request.

2. On a side note, what's even more strange is that Roboflow API would create the same `id` (`WXhyfRvH8o7idrl3T3SR`) for two consecutive images. Seems like this shouldn't happen (I get different `id`s even if I upload the same image twice).

3. I found that sometimes the images require a page refresh to show up.  are you able to see anything under:
[(https://app.roboflow.com/tl-ryah5/stuff-blpdm/images/](https://app.roboflow.com/tl-ryah5/stuff-blpdm/images/)?

4. For debugging, could you try the same set of parameters on my dataset + API key and show the resulting console output? The command below seems to be working fine on my machine:
```
python3 main.py --dataset stuff-blpdm --api_key mwRWRi5DtIYZUqzdYlxj  --upload_res 640x360 --autoupload_interval 0.5 --autoupload_threshold 0.7
```

**Comment by VanDavv** [comment]
I guess this must have been something on the Roboflow side, I didn't see any images being uploaded but as I run it now, it works fine with both mine and your arguments.
Will merge this PR and add my fixes later (mostly blobconverter usage).

Thanks a lot!

**Pull request merged**
