### PR TITLE
Migrate RTSP streaming experiment to Gen2 (with hw encoding)

### LINKED ISSUE #160: Migrate RSTP streaming example to Gen2
We should migrate [rstp streaming example](https://github.com/luxonis/depthai-experiments/tree/master/rtsp-streaming) to Gen2.

Together with this migration, we can try to follow [this suggestion](https://github.com/luxonis/depthai/issues/294#issuecomment-881815401) in order to optimize CPU usage on the host

### PR DESCRIPTION
**Pull request by VanDavv**
This PR migrates RTSP streaming example to Gen2, resolves #160 .
GStreamer launch code was simplified and DepthAI uses it's own VideoEncoder node to encode RGB stream into H.265, which is then fed into RTSP server on the host and shared over the network.

Testable using
```
cd gen2-rtsp-streaming
python3 main.py
# in other window
ffplay rtsp://localhost:8554/preview
```

### CODE REVIEW

**Review by Erol444 — APPROVED** [review]
Works great on ubuntu :+1: Haven't tested yet on mac/windows

**Comment by Luxonis-Brandon** [comment]
Thanks for migrating this.  Will try hopefully today.

**Comment by VanDavv** [comment]
I'm testing it now on Mac, have some additional gstreamer install instructions for OSX, and will commit them shortly, CC @Luxonis-Brandon

**Comment by Luxonis-Brandon** [comment]
Thanks @VanDavv .  I'll give it a test too when you upload the instructions.  Appreciate you testing it on the Mac as well.

**Comment by VanDavv** [comment]
@Luxonis-Brandon updated the install instructions with OSX required packages, in short, the following commands should be enough to install all dependencies and run on Big Sur

```
cd gen2-rtsp-streaming
brew install pkg-config cairo gobject-introspection gst-plugins-bad gst-plugins-base gstreamer gst-rtsp-server ffmpeg gst-plugins-good
python3 -m pip install -r requirements.txt
python3 main.py
# in other terminal session
ffplay rtsp://localhost:8554/preview
```

**Comment by Luxonis-Brandon** [comment]
Sorry behind on everything.  Feel free to merge w/out me.

**Pull request merged**
