### PR TITLE
Gen2 Stereo demo updates

### PR DESCRIPTION
**Pull request by alex-luxonis**

### CODE REVIEW

**Comment by alex-luxonis** [comment]
DepthAI library source code PR: https://github.com/luxonis/depthai-python/pull/67

**Comment by alex-luxonis** [comment]
The USB3 issue present on Mac with Gen2 (failure to find the device after boot) seems to be resolved with the latest updates.

**Comment by Luxonis-Brandon** [comment]
Sweet!  Testing this now.

**Review by Luxonis-Brandon — APPROVED** [review]
First confirmed that on `master` the issue still exists (by forgetting to switch branches):
```
leeroy@DESKTOP-OGSI4CI gen2-camera-demo % python3 main.py
StereoDepth config options:
    Left-Right check:   True
    Extended disparity: False
    Subpixel:           True
    Median filtering:   MedianFilter.MEDIAN_OFF
Creating Stereo Depth pipeline: MONO CAMS -> STEREO -> XLINK OUT
Creating DepthAI device
Traceback (most recent call last):
  File "main.py", line 302, in <module>
    test_pipeline()
  File "main.py", line 230, in test_pipeline
    device = dai.Device()
RuntimeError: Failed to find device after booting, error message: X_LINK_DEVICE_NOT_FOUND
```

Then ran:
```
git checkout gen2_stereo_update 
python3 -m pip install -r requirements.txt
python3 main.py 
```

image

Works great!  Very satisfying to have USB3 rates on macOS.

**Pull request merged**
