### PR TITLE
Updated gaze estimation to depthai 2.15

### PR DESCRIPTION
**Pull request by Erol444**

### CODE REVIEW

**Review by VanDavv — APPROVED** [review]
Demo works great, thanks!
The only thing I noticed is that I got SIGSEGV when exiting the program, but this may be regression so posting here for further investigation
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
Exception in thread Thread-2:
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/vandavv/dev/depthai-experiments/gen2-gaze-estimation/main.py", line 234, in land_pose_thread
    land_in = landmark_nn.get().getFirstLayerFp16()
AttributeError: 'NoneType' object has no attribute 'getFirstLayerFp16'
    self._target(*self._args, **self._kwargs)
  File "/Users/vandavv/dev/depthai-experiments/gen2-gaze-estimation/main.py", line 207, in face_thread
    bboxes = np.array(face_nn.get().getFirstLayerFp16())
AttributeError: 'NoneType' object has no attribute 'getFirstLayerFp16'
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/vandavv/dev/depthai-experiments/gen2-gaze-estimation/main.py", line 288, in gaze_thread
    self.gaze = np.array(gaze_nn.get().getFirstLayerFp16())
AttributeError: 'NoneType' object has no attribute 'getFirstLayerFp16'
Stack trace (most recent call last):
#18   Object "Python3", at 0x10905e62b, in Py_BytesMain + 43
#17   Object "Python3", at 0x10905e5d3, in pymain_main + 403
#16   Object "Python3", at 0x10905e0a7, in Py_RunMain + 2103
#15   Object "Python3", at 0x10903e6e4, in PyRun_SimpleFileExFlags + 276
#14   Object "Python3", at 0x10903f283, in PyRun_FileExFlags + 291
#13   Object "Python3", at 0x108fed5e0, in PyEval_EvalCode + 48
#12   Object "Python3", at 0x108ff96d4, in _PyEval_EvalCodeWithName + 3268
#11   Object "Python3", at 0x108ff48f2, in _PyEval_EvalFrameDefault + 29298
#10   Object "Python3", at 0x108f1a694, in method_vectorcall + 516
#9    Object "Python3", at 0x108f171d6, in _PyObject_MakeTpCall + 374
#8    Object "Python3", at 0x108f1778a, in cfunction_call_varargs + 122
#7    Object "depthai.cpython-38-darwin.so", at 0x12e41e649, in PyInit_depthai + 39497
#6    Object "depthai.cpython-38-darwin.so", at 0x12e451ecd, in PyInit_depthai + 250573
#5    Object "depthai.cpython-38-darwin.so", at 0x12e2862c9, in dai::Device::closeImpl() + 553
#4    Object "depthai.cpython-38-darwin.so", at 0x12e2f007b, in dai::DataInputQueue::send(dai::ADatatype const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >) + 203
#3    Object "depthai.cpython-38-darwin.so", at 0x12e2f0146, in dai::DataInputQueue::send(dai::ADatatype const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >) + 406
#2    Object "libsystem_platform.dylib", at 0x7fff204b7d7c, in _sigtramp + 28
#1    Object "depthai.cpython-38-darwin.so", at 0x12e36368d, in backward::SignalHandling::sig_handler(int, __siginfo*, void*) + 13
#0    Object "depthai.cpython-38-darwin.so", at 0x12e3636f6, in backward::SignalHandling::sig_handler(int, __siginfo*, void*) + 118
```

**Comment by VanDavv** [comment]
After a second run I got also AttributeErrors:
```
Stack trace (most recent call last) in thread 13011693568:
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self.gaze = np.array(gaze_nn.get().getFirstLayerFp16())
AttributeError: 'depthai.ADatatype' object has no attribute 'getFirstLayerFp16'
    self._target(*self._args, **self._kwargs)
  File "main.py", line 234, in land_pose_thread
    land_in = landmark_nn.get().getFirstLayerFp16()
AttributeError: 'depthai.ADatatype' object has no attribute 'getFirstLayerFp16'
```

Full log

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "main.py", line 288, in gaze_thread
Stack trace (most recent call last) in thread 13011693568:
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self.gaze = np.array(gaze_nn.get().getFirstLayerFp16())
AttributeError: 'depthai.ADatatype' object has no attribute 'getFirstLayerFp16'
    self._target(*self._args, **self._kwargs)
  File "main.py", line 234, in land_pose_thread
    land_in = landmark_nn.get().getFirstLayerFp16()
AttributeError: 'depthai.ADatatype' object has no attribute 'getFirstLayerFp16'
#25   Object "libsystem_pthread.dylib", at 0x7fff204728fc, in _pthread_start + 224
#24   Object "Python3", at 0x10abe41b9, in pythread_wrapper + 25
#23   Object "Python3", at 0x10ac32fda, in t_bootstrap + 74
#22   Object "Python3", at 0x10aaaf524, in PyVectorcall_Call + 100
#21   Object "Python3", at 0x10aab25d2, in method_vectorcall + 322
#20   Object "Python3", at 0x10aaafb8d, in function_code_fastcall + 237
#19   Object "Python3", at 0x10ab8ccff, in _PyEval_EvalFrameDefault + 30335
#18   Object "Python3", at 0x10ab90662, in call_function + 354
#17   Object "Python3", at 0x10aaafb8d, in function_code_fastcall + 237
#16   Object "Python3", at 0x10ab8ccff, in _PyEval_EvalFrameDefault + 30335
#15   Object "Python3", at 0x10ab90662, in call_function + 354
#14   Object "Python3", at 0x10aaafb8d, in function_code_fastcall + 237
#13   Object "Python3", at 0x10ab8d07d, in _PyEval_EvalFrameDefault + 31229
#12   Object "Python3", at 0x10aaaf524, in PyVectorcall_Call + 100
#11   Object "Python3", at 0x10aab25d2, in method_vectorcall + 322
#10   Object "Python3", at 0x10aaafb8d, in function_code_fastcall + 237
#9    Object "Python3", at 0x10ab8cd1c, in _PyEval_EvalFrameDefault + 30364
#8    Object "Python3", at 0x10ab90662, in call_function + 354
#7    Object "Python3", at 0x10aab2575, in method_vectorcall + 229
#6    Object "Python3", at 0x10aaaf1d6, in _PyObject_MakeTpCall + 374
#5    Object "Python3", at 0x10aaaf78a, in cfunction_call_varargs + 122
#4    Object "depthai.cpython-38-darwin.so", at 0x12fffb649, in PyInit_depthai + 39497
#3    Object "depthai.cpython-38-darwin.so", at 0x1301119fe, in PyInit_depthai + 1179134
#2    Object "libsystem_platform.dylib", at 0x7fff204b7d7c, in _sigtramp + 28
#1    Object "depthai.cpython-38-darwin.so", at 0x12ff4068d, in backward::SignalHandling::sig_handler(int, __siginfo*, void*) + 13
#0    Object "depthai.cpython-38-darwin.so", at 0x12ff406f6, in backward::SignalHandling::sig_handler(int, __siginfo*, void*) + 118
zsh: segmentation fault  python main.py -cam
```

**Comment by Erol444** [comment]
@VanDavv  I would guess that hapens because disposing threads isn't working as supposed to when closing the program. But not sure how you got the ADatatype error, seems strange NeuralNetwork node would output that.

**Comment by themarpe** [comment]
@Erol444 do a check after getting a message from the queue - upon first glance, not sure how it doesn't throw an exception instead, but still, would resolve the issue (eg check if its an instanceof the required message type)

**Comment by rexn8r** [comment]
Thanks working!!!

**Pull request merged**
