### PR TITLE
Reid performance improvements

### PR DESCRIPTION
**Pull request by themarpe**
This changes affect:
 - Added identification and reidentification blobs compiled for 4 shaves to better distribute resources
 - Infer only on most recent frames while still keep in sync with source video / camera
 - Decreased latency dramatically
 
**Note**: use `main_threaded.py` for testing this PR. I haven't worked on original `main.py` script for current changes.

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Thanks!  Trying now.

**Comment by themarpe** [comment]
@Luxonis-Brandon have to update `requirements.txt` - I've used some recent features.
One minute

**Comment by Luxonis-Brandon** [comment]
Got it thanks.  Actually I was just about to ask as I saw: 
```
Traceback (most recent call last):
  File "main_threaded.py", line 346, in <module>
    app.run()
  File "main_threaded.py", line 272, in run
    pipeline = create_pipeline()
  File "main_threaded.py", line 65, in create_pipeline
    detection_nn.setNumInferenceThreads(2)
AttributeError: 'depthai.MobileNetDetectionNetwork' object has no attribute 'setNumInferenceThreads'
```

And was wondering if I hadn't properly updated yet.

**Comment by themarpe** [comment]
Updated depthai dependency in `requirements.txt`. PR is ready now

**Comment by Luxonis-Brandon** [comment]
Thanks trying it now.

**Comment by Luxonis-Brandon** [comment]
Just tried real quick.  Could be a PEBKAC error:

```
git pull                                  
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/luxonis/depthai-experiments
   30dbbf2..78e211e  reid_performance_improvements -> origin/reid_performance_improvements
Updating 30dbbf2..78e211e
Fast-forward
 gen2-pedestrian-reidentification/requirements.txt | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
brandongilles@Leeroys-MBP-2 gen2-pedestrian-reidentification % python3 -m pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local/
Requirement already satisfied: opencv-python==4.5.1.48 in /Users/brandongilles/Library/Python/3.8/lib/python/site-packages (from -r requirements.txt (line 1)) (4.5.1.48)
Requirement already satisfied: imutils==0.5.4 in /Users/brandongilles/Library/Python/3.8/lib/python/site-packages (from -r requirements.txt (line 2)) (0.5.4)
Collecting depthai==0.0.2.1+5cd4297f35cd44744886b6cf52c7413bbb4bc8c3
  Downloading https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local/depthai/depthai-0.0.2.1%2B5cd4297f35cd44744886b6cf52c7413bbb4bc8c3-cp38-cp38-macosx_10_9_x86_64.whl (4.5 MB)
     |████████████████████████████████| 4.5 MB 1.9 MB/s 
Requirement already satisfied: numpy>=1.17.3 in /Users/brandongilles/Library/Python/3.8/lib/python/site-packages (from opencv-python==4.5.1.48->-r requirements.txt (line 1)) (1.19.5)
Installing collected packages: depthai
  Attempting uninstall: depthai
    Found existing installation: depthai 0.0.2.1+e1e2f25e12fb77c7e9d4392ecc0c338e1a4117c7
    Uninstalling depthai-0.0.2.1+e1e2f25e12fb77c7e9d4392ecc0c338e1a4117c7:
      Successfully uninstalled depthai-0.0.2.1+e1e2f25e12fb77c7e9d4392ecc0c338e1a4117c7
Successfully installed depthai-0.0.2.1+5cd4297f35cd44744886b6cf52c7413bbb4bc8c3
WARNING: You are using pip version 20.3.1; however, version 21.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
brandongilles@Leeroys-MBP-2 gen2-pedestrian-reidentification % python3 main_threaded.py -vid ./input.mp4 
depthai module:  /Users/brandongilles/Library/Python/3.8/lib/python/site-packages/depthai.cpython-38-darwin.so
framerate:  29.97002997002997
Creating pipeline...
Creating Person Detection Neural Network...
Creating Person Reidentification Neural Network...
Pipeline created.
Starting pipeline...
[14442C107138BFD200] [4756.993] [NeuralNetwork(5)] [warning] Number of inference threads assigned for network is 1, assigning 2 will likely yield in better performance
[14442C107138BFD200] [4756.993] [NeuralNetwork(5)] [warning] Network compiled for 4 shaves, maximum available 16, compiling for 8 shaves likely will yield in better performance
[14442C107138BFD200] [4756.994] [DetectionNetwork(0)] [warning] Network compiled for 4 shaves, maximum available 16, compiling for 8 shaves likely will yield in better performance
[14442C107138BFD200] [4757.003] [NeuralNetwork(5)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
[14442C107138BFD200] [4757.003] [DetectionNetwork(0)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
2021-02-19 09:59:48.762 Python[50607:4668993] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff204806af __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff201b83c9 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff204a8a9a -[NSException raise] + 9
	3   AppKit                              0x00007fff22c4897d -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321
	4   AppKit                              0x00007fff22c336d5 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1375
	5   AppKit                              0x00007fff22c3316f -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	6   AppKit                              0x00007fff22f3d2c8 -[NSWindow initWithContentRect:styleMask:backing:defer:screen:] + 52
	7   cv2.cpython-38-darwin.so            0x000000010916bed5 cvNamedWindow + 677
	8   cv2.cpython-38-darwin.so            0x000000010916b79c cvShowImage + 188
	9   cv2.cpython-38-darwin.so            0x0000000109169c66 _ZN2cv6imshowERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS_11_InputArrayE + 230
	10  cv2.cpython-38-darwin.so            0x00000001083cb39e _ZL18pyopencv_cv_imshowP7_objectS0_S0_ + 302
	11  Python3                             0x0000000107bf538a cfunction_call_varargs + 122
	12  Python3                             0x0000000107bf4dd6 _PyObject_MakeTpCall + 374
	13  Python3                             0x0000000107cd513c call_function + 652
	14  Python3                             0x0000000107cd16d6 _PyEval_EvalFrameDefault + 29782
	15  Python3                             0x0000000107bf578d function_code_fastcall + 237
	16  Python3                             0x0000000107bf81e2 method_vectorcall + 322
	17  Python3                             0x0000000107bf5124 PyVectorcall_Call + 100
	18  Python3                             0x0000000107cd1a34 _PyEval_EvalFrameDefault + 30644
	19  Python3                             0x0000000107bf578d function_code_fastcall + 237
	20  Python3                             0x0000000107cd5012 call_function + 354
	21  Python3                             0x0000000107cd16b9 _PyEval_EvalFrameDefault + 29753
	22  Python3                             0x0000000107bf578d function_code_fastcall + 237
	23  Python3                             0x0000000107cd5012 call_function + 354
	24  Python3                             0x0000000107cd16b9 _PyEval_EvalFrameDefault + 29753
	25  Python3                             0x0000000107bf578d function_code_fastcall + 237
	26  Python3                             0x0000000107bf81e2 method_vectorcall + 322
	27  Python3                             0x0000000107bf5124 PyVectorcall_Call + 100
	28  Python3                             0x0000000107d7700a t_bootstrap + 74
	29  Python3                             0x0000000107d28829 pythread_wrapper + 25
	30  libsystem_pthread.dylib             0x00007fff2030e950 _pthread_start + 224
	31  libsystem_pthread.dylib             0x00007fff2030a47b thread_start + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
zsh: abort      python3 main_threaded.py -vid ./input.mp4

```

**Review by szabi-luxonis — CHANGES_REQUESTED** [review]
There are 16 shaves available, 4 allocated for each network, total of 3 threads. Compiling first stage network `person-detection-retail-0013` for 6 shaves instead 4 will be faster. Although just by a few FPS.
For video only case, not running from camera.

**Comment by szabi-luxonis** [comment]
Tried it, and runs fine. Compiling for 6 shaves for video case improves FPS only by 1 fps, so disregard.
Remove old blobs though.

**Comment by themarpe** [comment]
@Luxonis-Brandon retesting on mac - didn't experience on Ubuntu.

**Comment by themarpe** [comment]
@szabi-luxonis there is also the `-cam` option which would require another set of blobs so I just went with "common" denominator (not really but close)

Will remove the other `main.py` and blobs

**Comment by Luxonis-Brandon** [comment]
> @Luxonis-Brandon retesting on mac - didn't experience on Ubuntu.

Yes, it seems like it is a Mac-specific thing based on the error message.  It actually seems to be something with how Python is interacting with windowing in macOS and how the threading is being handled.

**Review by szabi-luxonis — APPROVED** [review]

**Comment by themarpe** [comment]
Latest changes completely remove previous code and blobs in favor of this implementation.
- Modified the example to use source (high resolution) frames by default, can be disabled using `-lq`
- Added `-w` parameter to set output visualization width
- Fixed macOS crash
- Updated README.md

**Review by Luxonis-Brandon — APPROVED** [review]
Works great for me now.  Not much delay at all even when live from the camera.

**Pull request merged**
